metadata:
  name: devops-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app 
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: devops-container
        image: hrnaltun/devops:v1
        ports:
        - containerPort: 8080
